//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoMedios
    {
        public int ContactoMedioId { get; set; }
        public int ContactoId { get; set; }
        public int TipoContactoId { get; set; }
        public string Valor { get; set; }
    
        public virtual Contactos Contactos { get; set; }
        public virtual TiposContacto TiposContacto { get; set; }
    }
}
